name: Ping Web Site

on:
  push:
    branches: [ master ]
  schedule: 
    - cron: '*/7 * * * *' 
jobs:
  ping:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet tool install Web.Ping -g
    - name: Ping ytsite.aqingyuan.repl.co
      run: Web.Ping --host https://ytsite.aqingyuan.repl.co
    - name: Ping ytsite.aqingyuan.repl.co
      run: Web.Ping --host https://ytsite.aqingyuan.repl.co
    - name: Ping ytsite.aqingyuan.repl.co
      run: Web.Ping --host ytsite.aqingyuan.repl.co
    - name: Ping ytsite.aqingyuan.repl.co
      run: Web.Ping --host https://ytsite.aqingyuan.repl.co
    - name: Ping ytsite.aqingyuan.repl.co
      run: Web.Ping --host https://ytsite.aqingyuan.repl.co




